# Generated by Django 3.2.4 on 2021-06-30 04:15

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PAINTING', 'Painting'), ('MUSIC', 'Music'), ('MOVIE', 'Movie'), ('BOOK', 'BooK')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('pub_year', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artwork_type', models.CharField(choices=[('PAINTING', 'Painting'), ('MUSIC', 'Music'), ('MOVIE', 'Movie'), ('BOOK', 'BooK')], max_length=30)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('artwork', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='artworks.artwork')),
                ('pages', models.IntegerField()),
                ('cover', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=75, size=[1024, 1024], upload_to='books/covers/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('artwork', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='artworks.artwork')),
                ('media_type', models.CharField(choices=[('MUSIC', 'Music'), ('VIDEO', 'Video')], max_length=10)),
                ('duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('artwork', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='artworks.artwork')),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('paint', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='artwork',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artworks.author'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artworks.genre'),
        ),
    ]
