# Generated by Django 3.2.4 on 2021-07-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0002_auto_20210630_0857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('artwork_type',)},
        ),
        migrations.AlterField(
            model_name='artwork',
            name='type',
            field=models.CharField(choices=[('', '-----------'), ('PAINTING', 'Painting'), ('MUSIC', 'Music'), ('MOVIE', 'Movie'), ('BOOK', 'Book')], max_length=30),
        ),
        migrations.AlterField(
            model_name='genre',
            name='artwork_type',
            field=models.CharField(choices=[('', '-----------'), ('PAINTING', 'Painting'), ('MUSIC', 'Music'), ('MOVIE', 'Movie'), ('BOOK', 'Book')], max_length=30),
        ),
        migrations.AlterField(
            model_name='painting',
            name='height',
            field=models.IntegerField(verbose_name='Height (cm)'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='width',
            field=models.IntegerField(verbose_name='Width (cm)'),
        ),
    ]
