# Generated by Django 3.2.4 on 2021-07-02 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0003_auto_20210702_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='painting',
            name='width',
            field=models.IntegerField(),
        ),
    ]
